### ISSUE TITLE
Cannot close preview window with q if termwinkey is set

### ISSUE THREAD

**Issue by mmktomato** [skanehira/preview-markdown.vim#15]
Preview window doesn't close and receive any keys when I type `q`.

I found it happens if `termwinkey` is set to another key that is not `<C-w>`. Like:
```
set termwinkey=<C-l>
```
It goes fine if I remove above line from my vimrc.

**Comment by skanehira** [comment]
What kind of parser did you use?
`q` is just vim key map, If parser is `mdr` and it running, we cannot use vim key map.

https://github.com/skanehira/preview-markdown.vim/blob/e34d59f6f0588ae3a7d45eb6cf11ed4379b8334c/autoload/preview_markdown.vim#L110

**Comment by mmktomato** [comment]
I use `mdr`.
The line you mentioned seems to close preview window and terminate `mdr` job.
But it doesn't go fine if `termwinkey` is overridden because `<C-w>` is the default value of `termwinkey`.
Is there any way to avoid this even if I set `termwinkey` to another value?

**Comment by skanehira** [comment]
Oh, I got it.
I'm Sorry, this implementation not considered if termwinkey be changed.
I'll fix this problem, please wait a little.

**Comment by skanehira** [comment]
@mmktomato I fixed this problem.
Please update plugin and try it.

**Comment by mmktomato** [comment]
The latest version doesn't fix the problem... Nothing changes.

I tried the following lines in my vimrc:
```
set termwinkey=<C-l>
echo printf('tnoremap <buffer> <silent> q %s:bw! \| call <SID>stop_job()<CR>', &termwinkey ? &termwinkey : '<C-w>')
```
And I got `tnoremap <buffer> <silent> q <C-w>:bw! \| call <SID>stop_job()<CR>`.
I guess that `&termwinkey ? &termwinkey : '<C-w>'` doesn't work fine.

**Comment by skanehira** [comment]
Oh sorry, my implementation was not enough.
I fixed it, please update plugin and try it.

**Comment by mmktomato** [comment]
It works very good. Thank you for the quick fix!!
